#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
USER_BASE_PATH="$(python -m site --user-base)"
export PATH=$USER_BASE_PATH:$PATH

alias z='fasd_cd -d'
alias c='code .'
alias gg="git gui &"
alias gup="gitup"
alias gbda='git branch --no-color --merged | command grep -vE "^(\*|\s*(master|develop|dev)\s*$)" | command xargs -n 1 git branch -d'

[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion
fpath=(/usr/local/share/zsh-completions $fpath)

eval "$(hub alias -s)"
