#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
USER_BASE_PATH="$(python -m site --user-base)"
export PATH=$USER_BASE_PATH:$PATH

alias gup="gitup"

eval "$(hub alias -s)"
